# Generated by Django 3.1.2 on 2020-10-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=12)),
                ('contraseña', models.CharField(max_length=20)),
                ('contraseña2', models.CharField(max_length=20)),
            ],
        ),
    ]
